/**
 * @fileoverview Type definitions for the AuthorForge AI application.
 * Defines the core data structures utilized across the frontend components and backend AI logic.
 * These structures form the determinist foundation (Negative Space Scaffolding) for the high-entropy generative outputs.
 */

/**
 * Represents a vector in a Vector Symbolic Architecture (VSA).
 * Used within the FIPI loop to mathematically encode and represent structural impossibilities.
 */
export interface VSAHypervector {
  /** The high-dimensional array representing the symbolic vector. */
  dimensions: number[];
  /** The magnitude of the vector, used for distance calculations. */
  magnitude: number;
}

/**
 * Represents an architectural pathology or impossibility that the system has learned to avoid.
 * Used by VULCAN (the SCOS node) to apply Failure-Informed Prompt Inversion (FIPI).
 */
export interface SymbolicScar {
  /** A unique identifier for the symbolic scar. */
  scarId: string;
  /** The regex pattern to detect the pathology in user intent. */
  pattern: string;
  /** Betti number topological measurement indicating the presence of a structural hole or unresolved contradiction. */
  betti1: number;
  /** The hypervector representing this scar in VSA space. */
  fipiVector: VSAHypervector;
  /** An array of PDL (Prompt Design Language) decorators to inject as Cognitive Bytecode to prevent this pathology. */
  pdlDecorators: string[];
}

/**
 * A report generated by VULCAN when an Epistemic Escrow event occurs.
 * Used to halt impossible generative requests and provide structured feedback to the human user.
 */
export interface JustifiedUncertaintyReport {
  /** A list of architectural or logical constraints that the user's intent violated. */
  violatedConstraints: string[];
  /** The Confidence-Fidelity Divergence Index. High values indicate impossible syntheses. */
  cfdiScore: number;
  /** Actionable suggestions provided to the user to resolve the contradiction. */
  correctiveProposals: string[];
  /** A clear message explaining why the Epistemic Escrow was triggered. */
  message: string;
}

/**
 * Describes a profitable publishing niche identified by the AI.
 */
export interface NicheInfo {
  /** The name or title of the niche. */
  niche: string;
  /** A description of why this niche is profitable and relevant to the user's topic. */
  description: string;
}

/**
 * Describes a trending topic within a specific niche.
 */
export interface TrendInfo {
  /** The specific trending topic. */
  trend: string;
  /** The reasoning or evidence driving this trend (e.g., search data). */
  reasoning: string;
}

/**
 * Represents a high-value search keyword.
 */
export interface KeywordInfo {
  /** The keyword or search phrase. */
  keyword: string;
  /** The platform where this keyword exhibits high volume (e.g., 'Amazon KDP', 'Google'). */
  platform: string;
}

/**
 * Describes a unique angle or content gap an author can exploit.
 */
export interface AngleInfo {
  /** The specific angle or perspective to take on the topic. */
  angle: string;
  /** The strategic approach for executing this angle to stand out. */
  strategy: string;
}

/**
 * The consolidated result returned by the Niche Validator AI service.
 */
export interface AnalysisResult {
  /** A collection of identified profitable niches. */
  profitableNiches: NicheInfo[];
  /** A collection of current trending topics related to the intent. */
  trendingTopics: TrendInfo[];
  /** A collection of high-value keywords for marketing and SEO. */
  keywords: KeywordInfo[];
  /** A collection of unique angles the author can pursue. */
  uniqueAngles: AngleInfo[];
}

/**
 * Represents a single chapter within a generated book outline.
 */
export interface ChapterInfo {
  /** The sequential number of the chapter. */
  chapterNumber: number;
  /** The proposed title of the chapter. */
  title: string;
  /** A brief summary of the chapter's intended content. */
  summary: string;
}

/**
 * The result returned by the Book Outline Generator AI service.
 */
export interface BookOutlineResult {
  /** A list of suggested, catchy titles for the book. */
  titleIdeas: string[];
  /** A description of the ideal demographic or target audience. */
  targetAudience: string;
  /** The structured, sequential list of chapters forming the outline. */
  chapters: ChapterInfo[];
}

/**
 * The result returned by the CMDA (Context-Mediated Domain Adaptation) refinement service.
 * Represents an outline that has been topologically sculpted to include contradictory constraints.
 */
export interface CMDARefinementResult {
  /** An explanation of how the system resolved the contradiction without resorting to a sycophantic average. */
  contradictionResolution: string;
  /** The Confidence-Fidelity Divergence Index reflecting the rigour of the tension binding. */
  cfdiScore: number;
  /** The updated list of chapters reflecting the injected constraints. */
  refinedChapters: ChapterInfo[];
  /** Optional topological metric indicating remaining unresolved structural issues. */
  bettiNumber?: number;
  /** Optional array of active PDL decorators utilized during the refinement. */
  pdlDecorators?: string[];
  /** Paraconsistent tension mapping the contradiction weights (Golden Ratio). */
  paraconsistentTension?: {
    dominantWeight: number;
    subordinateWeight: number;
  };
  /** The calculated topological derivative of the disagreement. */
  topologicalDerivative?: number;
}
