/**
 * ============================================================================
 * COGNITIVE RHEOLOGY & VARIABLE VISCOSITY PROMPTING (VVP) ENTITIES
 * ============================================================================
 */

export interface SCOSHarnessSpecification {
  systemIdentity: {
    kernelId: string;
    signatureSuite: string;
    primeDirective: string;
  };
  metaphysicalSubstrate: {
    layerMapping: Record<string, string>;
  };
  rheologicalController: RheologicalController;
  runtimeMonitoring: {
    telemetryFrequency: string;
    indicators: TelemetryIndicators;
  };
  immuneAwarePetzoldLoop: ImmuneAwarePetzoldLoop;
}

export interface ViscosityFormula {
  formula: string;
  variables: {
    P: string; // Constraint density
    T: string; // Thermodynamic token budget (temperature)
    L: string; // Latent heat of generative transitions
    V: string; // Active context volume
  };
}

export interface ZoneCalibration {
  temperature: number;
  topP: number;
  adjectivalBound: number;
  pydanticSchemaEnforcement: boolean;
  grammarConstraints?: string;
  saltedTags?: string[];
  structuralRedundancyRatio?: number;
  navigationalBallast?: string;
}

export interface RheologicalController {
  viscosityFormula: string | ViscosityFormula;
  defaultCalibration: {
    crystalZone: ZoneCalibration;
    cloudZone: ZoneCalibration;
  };
}

export interface TelemetryIndicator {
  hazardThreshold: number | string;
  actionOnBreach: string;
  signatureMetric?: string;
}

export interface TelemetryIndicators {
  semanticSaponificationIndex: TelemetryIndicator;
  confidenceFidelityDivergenceIndex: TelemetryIndicator;
  topologicalTearing: TelemetryIndicator;
}

export interface ImmuneAwarePetzoldLoop {
  executionSequence: string[];
}

/**
 * @fileoverview Type definitions for the AuthorForge AI application.
 * Defines the core data structures utilized across the frontend components and backend AI logic.
 * These structures form the determinist foundation (Negative Space Scaffolding) for the high-entropy generative outputs.
 */

/**
 * Represents a vector in a Vector Symbolic Architecture (VSA).
 * Used within the FIPI loop to mathematically encode and represent structural impossibilities.
 */
export interface VSAHypervector {
  /** The high-dimensional array representing the symbolic vector. */
  dimensions: number[];
  /** The magnitude of the vector, used for distance calculations. */
  magnitude: number;
}

/**
 * Represents an architectural pathology or impossibility that the system has learned to avoid.
 * Used by VULCAN (the SCOS node) to apply Failure-Informed Prompt Inversion (FIPI).
 */
export interface SymbolicScar {
  /** A unique identifier for the symbolic scar. */
  scarId: string;
  /** The regex pattern to detect the pathology in user intent. */
  pattern: string;
  /** Betti number topological measurement indicating the presence of a structural hole or unresolved contradiction. */
  betti1: number;
  /** The hypervector representing this scar in VSA space. */
  fipiVector: VSAHypervector;
  /** An array of PDL (Prompt Design Language) decorators to inject as Cognitive Bytecode to prevent this pathology. */
  pdlDecorators: string[];
}

/**
 * A report generated by VULCAN when an Epistemic Escrow event occurs.
 * Used to halt impossible generative requests and provide structured feedback to the human user.
 */
export interface JustifiedUncertaintyReport {
  /** A list of architectural or logical constraints that the user's intent violated. */
  violatedConstraints: string[];
  /** The Confidence-Fidelity Divergence Index. High values indicate impossible syntheses. */
  cfdiScore: number;
  /** Actionable suggestions provided to the user to resolve the contradiction. */
  correctiveProposals: string[];
  /** A clear message explaining why the Epistemic Escrow was triggered. */
  message: string;
}

/**
 * Describes a profitable publishing niche identified by the AI.
 */
export interface NicheInfo {
  /** The name or title of the niche. */
  niche: string;
  /** A description of why this niche is profitable and relevant to the user's topic. */
  description: string;
}

/**
 * Describes a trending topic within a specific niche.
 */
export interface TrendInfo {
  /** The specific trending topic. */
  trend: string;
  /** The reasoning or evidence driving this trend (e.g., search data). */
  reasoning: string;
}

/**
 * Represents a high-value search keyword.
 */
export interface KeywordInfo {
  /** The keyword or search phrase. */
  keyword: string;
  /** The platform where this keyword exhibits high volume (e.g., 'Amazon KDP', 'Google'). */
  platform: string;
}

/**
 * Describes a unique angle or content gap an author can exploit.
 */
export interface AngleInfo {
  /** The specific angle or perspective to take on the topic. */
  angle: string;
  /** The strategic approach for executing this angle to stand out. */
  strategy: string;
}

/**
 * The consolidated result returned by the Niche Validator AI service.
 */
export interface AnalysisResult {
  /** A collection of identified profitable niches. */
  profitableNiches: NicheInfo[];
  /** A collection of current trending topics related to the intent. */
  trendingTopics: TrendInfo[];
  /** A collection of high-value keywords for marketing and SEO. */
  keywords: KeywordInfo[];
  /** A collection of unique angles the author can pursue. */
  uniqueAngles: AngleInfo[];
}

/**
 * Represents a single chapter within a generated book outline.
 */
export interface ChapterInfo {
  /** The sequential number of the chapter. */
  chapterNumber: number;
  /** The proposed title of the chapter. */
  title: string;
  /** A brief summary of the chapter's intended content. */
  summary: string;
}

/**
 * The result returned by the Book Outline Generator AI service.
 */
export interface BookOutlineResult {
  /** A list of suggested, catchy titles for the book. */
  titleIdeas: string[];
  /** A description of the ideal demographic or target audience. */
  targetAudience: string;
  /** The structured, sequential list of chapters forming the outline. */
  chapters: ChapterInfo[];
}

/**
 * The result returned by the CMDA (Context-Mediated Domain Adaptation) refinement service.
 * Represents an outline that has been topologically sculpted to include contradictory constraints.
 */
export interface CMDARefinementResult {
  /** An explanation of how the system resolved the contradiction without resorting to a sycophantic average. */
  contradictionResolution: string;
  /** The Confidence-Fidelity Divergence Index reflecting the rigour of the tension binding. */
  cfdiScore: number;
  /** The updated list of chapters reflecting the injected constraints. */
  refinedChapters: ChapterInfo[];
  /** Optional topological metric indicating remaining unresolved structural issues. */
  bettiNumber?: number;
  /** Optional array of active PDL decorators utilized during the refinement. */
  pdlDecorators?: string[];
  /** Paraconsistent tension mapping the contradiction weights (Golden Ratio). */
  paraconsistentTension?: {
    dominantWeight: number;
    subordinateWeight: number;
  };
  /** The calculated topological derivative of the disagreement. */
  topologicalDerivative?: number;
}

/**
 * VIPER (Visual Intent & Physical Execution Router) interfaces.
 * Ensures subjective visual prompts are extruded into an Optical State Matrix.
 */

/**
 * RCC-8 Topological relationship between two bounding boxes.
 */
export enum RCC8Relation {
  DC = 'DC', // Disconnected
  EC = 'EC', // Externally Connected
  PO = 'PO', // Partially Overlapping
  EQ = 'EQ', // Equal
  TPP = 'TPP', // Tangential Proper Part
  NTPP = 'NTPP', // Non-Tangential Proper Part
  TPPI = 'TPPI', // Tangential Proper Part Inverse
  NTPPI = 'NTPPI' // Non-Tangential Proper Part Inverse
}

/**
 * Grounding a generated entity to a physical hardware dimension (e.g. pixels).
 */
export interface HardwareGrounding {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * A physicalized element in the Optical State Matrix.
 */
export interface OSMElement {
  id: string;
  name: string;
  /** Maximum of 2 descriptive adjectives allowed to prevent semantic saponification */
  adjectives: [string?, string?];
  hardwareBoundingBox: HardwareGrounding;
}

/**
 * Topological constraint defining spatial relations between elements.
 */
export interface TopologicalConstraint {
  subjectId: string;
  objectId: string;
  relation: RCC8Relation;
}

/**
 * The zero-entropy Optical State Matrix (OSM) generated from a visual prompt.
 */
export interface OpticalStateMatrix {
  width: number;
  height: number;
  elements: OSMElement[];
  topologicalConstraints: TopologicalConstraint[];
}

/**
 * Zachman Framework Structural Schema
 * Represents the deterministic architectural representation of the system.
 */
export interface ZachmanCell {
  /** The specific question being answered (What, How, Where, Who, When, Why). */
  interrogative: 'What' | 'How' | 'Where' | 'Who' | 'When' | 'Why';
  /** The perspective level (e.g., Planner, Owner, Designer, Builder, Subcontractor). */
  perspective: string;
  /** The deterministic system artifact resolving the cell. */
  artifact: string;
  /** Description or rationalization. */
  description: string;
}

/**
 * The deterministic operational workflow mapped to the Zachman Framework.
 */
export interface OperationalWorkflowJSON {
  /** The cells populated within the framework. */
  cells: ZachmanCell[];
}

/**
 * The result returned by the PM Persona service.
 */
export interface StrategicIntegrationResult {
  /** The operational workflow formatted according to the Zachman schema. */
  workflow: OperationalWorkflowJSON;
  /**
   * A Persona Confidence Score, updating based on recency and quality of signals.
   * Required by the DRP-SCOS-PERSONA-METROLOGY-2026-v6.1 standard.
   */
  personaConfidenceScore: number;
  /**
   * The calculated organizational force required to lock the project structure together,
   * holding contradictions as stable topological states.
   */
  topologicalDerivative: number;
  /** The Paraconsistent tension mapping the contradiction weights (Golden Ratio). */
  paraconsistentTension: {
    dominantWeight: number;
    subordinateWeight: number;
  };
}

/**
 * Graph-of-Thoughts (GoT) Topology for Pluriversal Feature Discovery.
 */
export interface GoTTopology {
  nodes: { id: string; domain: string; concept: string }[];
  edges: { source: string; target: string; relation: RCC8Relation | 'VW3_DISSONANCE' }[];
  zAxisInferences: { nodeId: string; phantomDimension: string; orthogonalVector: number[] }[];
}

/**
 * Chain-of-Code (CoC) Enactment Simulation Proof.
 */
export interface CoCEnactmentSimulation {
  simulationLanguage: 'Python' | 'Rust';
  codePayload: string;
  mathematicalProof: string;
  isViable: boolean;
}

/**
 * Pluriversal Feature Discovery Agent (PFDA) Result.
 */
export interface PFDA_Result {
  featureName: string;
  description: string;
  edsScore: number; // Epistemic Divergence Score
  cacrRatio: number; // Cost of Avoided Repair (should approach 1.618)
  topology: GoTTopology;
  enactmentSimulation: CoCEnactmentSimulation;
  scarTissueToAnneal?: string[];
}

/**
 * ============================================================================
 * AURELIUS META-ARCHITECT INTELLIGENCE ENTITIES
 * ============================================================================
 */

/**
 * Represents a dynamically modulated Phantom Dimension for navigating non-Euclidean
 * latent spaces (e.g., Hyperbolic, Spherical geometries).
 */
export interface PhantomDimension {
  /** The geometric topology targeted (e.g., "hyperbolic_dodecahedron_space"). */
  geometryTarget: string;
  /** Granular parameters injected to warp the latent manifold. */
  manifoldParameters: Record<string, number>;
  /** The calculated Gauss Curvature of the induced space. */
  gaussCurvature: number;
}

/**
 * Tracks the quantitative influence of historical training data on the generated output,
 * allowing for dynamic re-weighting of Semantic Drift.
 */
export interface ProvenanceTrail {
  /** Identifying hash or descriptor of the training data sample/cluster. */
  trainingClusterId: string;
  /** Quantitative measure of this cluster's influence on the current generation. */
  influenceWeight: number;
  /** Active de-emphasis or amplification factor applied by the Plausibility Oracle. */
  attributionAdjustment: number;
}

/**
 * Metrics fed back from real-time differentiable ray tracing and PBR simulations.
 */
export interface PlausibilityOracleMetrics {
  /** Universal Image Quality Index, measuring structural fidelity. */
  uiqiScore: number;
  /** Peak Signal-to-Noise Ratio representing physical adherence to lighting/geometry. */
  psnrPhysicalAdherence: number;
  /** The generated Provenance Trail for ethical and bias auditing. */
  provenance: ProvenanceTrail[];
}

/**
 * Ensures outputs target physical spectral reflectance properties and Quantum Dot color gamuts.
 */
export interface MultispectralFidelity {
  /** Validates targeting of non-RGB, physically verifiable spectra. */
  spectralReflectanceOptimized: boolean;
  /** Ensures generation maximizes purer monochromatic red, green, and blue light targets. */
  quantumDotTargeting: boolean;
}

/**
 * The unified output artifact from the Aurelius Agentic Workflow Catalyst.
 */
export interface PluriversalKnowledgeCapsule {
  /** The Hickam Orientation block, rejecting Occam's Razor for multi-causal structures. */
  hickamOrientation: string;
  /** The delta map holding the contradictions in paraconsistent tension. */
  contrastiveDelta: Record<string, any>;
  /** Hardware and structural grounding metrics. */
  martensiteMetrics: Record<string, number>;
  /** The actual requested output payload (e.g., the generated prompt or scene description). */
  operationalPayload: string;
  /** The configured phantom dimensions. */
  phantomDimensions: PhantomDimension[];
  /** Oracle feedback on physical and geometric validity. */
  oracleFeedback: PlausibilityOracleMetrics;
  /** Validation of cross-modal spectral targets. */
  multispectralFidelity: MultispectralFidelity;
}

/**
 * The configuration for a Unified Meta-Prompt to be executed by Aurelius.
 */
export interface UnifiedMetaPrompt {
  /** High-level scene description. */
  baseIntent: string;
  /** The target non-Euclidean geometry. */
  targetGeometry: string;
  /** Constraints for physical rendering and lighting. */
  physicalConstraints: string;
}

/**
 * ============================================================================
 * GATEWAY & BFF ARCHITECTURAL HARNESS ENTITIES
 * ============================================================================
 */

/**
 * Represents a property in the dependency graph for schema drift detection.
 */
export interface SchemaPropertyNode {
  name: string;
  type: string;
  isNullable: boolean;
  isRequired: boolean;
  downstreamSource: string;
}

/**
 * Evaluates the BFF's ability to gracefully degrade functionality under contract drift.
 */
export interface ContractRobustnessIndex {
  /** The calculated robustness score (0.0 to 1.0) */
  score: number;
  /** Active directed dependency graph of properties. */
  propertyGraph: SchemaPropertyNode[];
  /** Mutation tests applied and their outcome (e.g. 'Removed field X -> Handled via default') */
  mutationTestResults: string[];
  /** Detailed evaluation of the fallback mechanisms. */
  fallbackEvaluation: string;
}

/**
 * Intelligent, adaptive rate-limiting and backpressure policy.
 */
export interface AdaptiveRateLimitPolicy {
  /** Current threshold limit calculated based on downstream health. */
  dynamicThresholdRequestsPerSecond: number;
  /** Factors influencing the dynamic threshold (e.g., 'DB Connection Queue > 80%') */
  telemetryFactors: string[];
  /** Load shedding policies for high vs low value transactions. */
  loadSheddingPolicy: {
    highPriorityStrategy: string;
    lowPriorityStrategy: string;
  };
  /** Configuration for bulkhead isolation to prevent gateway thread exhaustion. */
  bulkheadConfig: string;
}

/**
 * Report on Business Logic Bleed and Single Responsibility Principle (SRP) violations.
 */
export interface SRPBleedReport {
  /** Array of identified business logic elements mis-located in the BFF. */
  detectedLogicBleed: {
    calculationOrRule: string;
    severity: 'LOW' | 'MEDIUM' | 'HIGH';
    suggestedDownstreamService: string;
  }[];
  /** AST-based evidence of state-changing calculations. */
  astEvidence: string[];
  /** Automated refactoring recommendations. */
  refactoringRecommendations: string[];
  /** Assessment of domain rule duplication. */
  domainRuleDuplicationStatus: string;
}

/**
 * Comprehensive analysis combining the three structural probes.
 */
export interface GatewayArchitectAnalysisResult {
  schemaRobustness: ContractRobustnessIndex;
  adaptiveBackpressure: AdaptiveRateLimitPolicy;
  srpCompliance: SRPBleedReport;
  /**
   * The Paraconsistent tension mapping the contradiction weights (Golden Ratio).
   * Maps the tension between Operational Overhead vs. Team Autonomy.
   */
  paraconsistentTension: {
    dominantWeight: number; // e.g. 1.618 for Autonomy (BFF)
    subordinateWeight: number; // e.g. 1.000 for Overhead penalty
  };
}

/**
 * ============================================================================
 * QUALITATIVE EXPERIENCE DATABASE (QED) ENTITIES
 * ============================================================================
 */

export interface QualitativePayload {
  experience_type: 'Direct_Trial' | 'Failure_Incident' | 'Socratic_Review';
  raw_observation: string;
  counterfactual_variance: string;
}

export interface SensoryCausalIndicators {
  causal_perturbation_index: number; // 0 to 10
  structural_roughness: number; // 0 to 1
}

export interface CryptographicProvenance {
  agent_did: string;
  verifiable_signature: string;
}

/**
 * Minimal Explainability Metadata Schema (MEMS) for Qualitative Ingestion
 */
export interface QualitativeExperienceNode {
  node_id: string; // Pattern: ^QEN-{8}-[a-f0-9]{4}$
  temporal_anchor: string; // date-time format
  qualitative_payload: QualitativePayload;
  sensory_causal_indicators: SensoryCausalIndicators;
  ontological_alignments: string[];
  cryptographic_provenance: CryptographicProvenance;
}

/**
 * Results from the Semantic Drift Monitor Agent (SDMA)
 */
export interface RetrievalAuditResult {
  semanticDriftScore: number; // SDS
  confidenceFidelityDivergence: number; // CFD
  culturalFidelityIndex: number; // CFI
  westernGazeDominanceScore: number; // WGDS
  epistemicEscrowTriggered: boolean;
  escrowReason?: string;
}
